### PR TITLE
Compatibility of Date.now() for IE8 and 7, opacity of backgrounds in …

### PR DESCRIPTION
**Pull request by gojohnkevin**
…IE8 and 7

### CODE REVIEW

**Comment by HTMLGuyLLC** [comment]
GREAT! Thank you!

**Comment by HTMLGuyLLC** [comment]
Can I mark this as being IE7+ compatible? I don't have 7 to test with.

**Comment by gojohnkevin** [comment]
Sure. No problem!

**Comment by HTMLGuyLLC** [comment]
Are you saying "No problem" for the "Thank you!" or the "IE7+ compatible"? lol. Just wondering if you had a chance to test thoroughly on IE7+. Thanks again.

**Comment by gojohnkevin** [comment]
Yes. I have tested in IE7+. We'll actually I would like to add more tweaks on the display.

**Comment by HTMLGuyLLC** [comment]
Let's see what you've got :)

**Pull request merged**
